branches:
  only:
  - master
  - gh-pages
language: node_js
node_js:
- '4.2.6'
install:
- npm install grunt-cli -g
- npm install --save-dev
script:
- grunt purge-cache
env:
  global:
  - CLOUDFLARE_DOMAIN: educast.pro
  - secure: 5YqtSk+e2a4W3NkZjkfixFQhthsk0hEbp7hRVqe7U5w8O0/Wt9WQmZfwrvWz+PfpAhnpUuJ6n5TwYI7o8UifeBirrYHcvyx2kZpl3iKoA3rcqjsG6mYfWcAfLkY37XRS6rsBzGVetp+DESq7iNmz6rRtNy0ixfycZoKXpYKP5oAJsTQRI+be7ILUMugLojvmNkSe2NF+f3aXZfKSiv0euw3xkRketroZWjvJHJzgRGr5GL5RvWaOeOt+sFD+TBk+vGUxVuFe+GD++0xzzK+Wfk5/rES6MoguNCvXqccwVZ3K9FwNIh4Ln515SJMEWBz9aipNzE1KeWittEkdilrEusL/sqrS//4Ljp8CS5Wu9v0eNNUQzwOfKzS5eiyOMlLeuO52in39aKAYJouP62fOLhsk4yv9nYcxtUfd0Y9iI68MobMRqAHol7po3bV0mwUZ4mhRmnsI0LJFNpGPne4hZ8+5/r6KanSyE4KJW4SdzDZchMhxKJ5URsw9uZlCrlrFNZvdtunrSXq12ILfZYCrn+dGgaEdZ74pnq899aTNKz4FdK8/yM8M+isoIRdt4yKUNUR4oudG6qwsaOHhsYLzmiS2wIGrVi5Z5qP/DdUc8n9EEA6FkNvKIHNqPFwIejFJz20uEbvlxl3vHI7gLBL9YXy/hUr/PmZh7aw6KpGiV/s=
  - secure: mchOrSDdHYI3C0yAb3vA4SzoCL4lwEL+KS0woz9EwSrSpIYs0Z/plCtoJsrpCuv2/afGmQjW2m5S6+tMG0JDupphj1PWHKKCjMLTinrmK8LMMZwlEGlWq8DBMJux39ZSivtcAN8+mowte5BtaudwQ/XFIIK63nBowvKlxJox2GE79W0/vAS9TXdYf3HqIvYVInnD201KK6KX6psG/IOOZZsDVXHvTb3dBksOVdY6l3Sja1cA+0mMYlkexyfKu83GyTv4hVzbJao7svIvmWgZ0twCK+n7K4vQGag72MZL+2KMKLm0KFAX83vGrqpU1BITTK5pvE1LAVKO8S7vrZ24e5qVNobX1EPajJ7ecJ9Uxix0wOS6b3LtQ2yQokQnj6/Gu/zA/JvcB53fVzulHZbR7w78VhXhclbrztTbYpjq9i4lKAuOvgJ3edd+Xbrt7g5rbK9Y3obsQrkQysLeKtcpzZCR9JR1+0TabH8VuBi6jkLOTnfcieVnSwAeesrZFmIZTLxarRECbpTVd85WT1nzs09JsBzATZ5GoKx+n4yCDn5oY08mBrINi907j6vD/iG2k7X4XFYWWpeWOdkJELo52ADl2RjbzTnZL23yzOA9OBZcXDsf5yxgvI5jK0CefsIm2zv3MPOIxS1kgVAJ9EeyeRZPjwdybcg+GtkJbFm1c8s=
